// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASFGuub4nfIPY-urjSZYpdUQPM-4Y8TSQ',
    appId: '1:830005811639:web:518552936480f1f71ef032',
    messagingSenderId: '830005811639',
    projectId: 'jupiter-clone',
    authDomain: 'jupiter-clone.firebaseapp.com',
    storageBucket: 'jupiter-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDMX6uEczpW3bZmWkniA8bt0x8ZVH9WtE',
    appId: '1:830005811639:android:680109666c76c11e1ef032',
    messagingSenderId: '830005811639',
    projectId: 'jupiter-clone',
    storageBucket: 'jupiter-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWsHRQhbm2D9VWYP4V0zviViowXPXCLo8',
    appId: '1:830005811639:ios:d4960500f50cd5381ef032',
    messagingSenderId: '830005811639',
    projectId: 'jupiter-clone',
    storageBucket: 'jupiter-clone.appspot.com',
    androidClientId: '830005811639-gkkru6jhfrdpgr782c53vd3el5h4kjld.apps.googleusercontent.com',
    iosClientId: '830005811639-g34dqit26bom388k30r1auo7gmjccbgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.jupiterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWsHRQhbm2D9VWYP4V0zviViowXPXCLo8',
    appId: '1:830005811639:ios:d4960500f50cd5381ef032',
    messagingSenderId: '830005811639',
    projectId: 'jupiter-clone',
    storageBucket: 'jupiter-clone.appspot.com',
    androidClientId: '830005811639-gkkru6jhfrdpgr782c53vd3el5h4kjld.apps.googleusercontent.com',
    iosClientId: '830005811639-g34dqit26bom388k30r1auo7gmjccbgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.jupiterClone',
  );
}
